export type MatchType = "EXACT" | "LIKELY" | "CONFLICT" | "NO MATCH";

export type ArmaTracFacts = {
  emission: string | null;
  modelName: string | null;
  serie: string | null;
  axle: string | null;
  cabinType: string | null;
  horsePower: number | null;
  usageType: string | null;
  gear: string | null;
  engine: string | null;
  torque: string | null;
  liftingCapacity: string | null;
  airConditioning: string | null;
};

export type ArmaTracSource = {
  id: string;
  url: string;
  label: string;
  facts: ArmaTracFacts;
  productId: string | null;
  match: MatchType;
  matchName: string | null;
  notes: string[];
  identityConflicts: string[];
  generationSafe: boolean;
  description: string | null;
};

export const ARMATRAC_SOURCES: ArmaTracSource[] = [
  {
    id: "1104-lux",
    url: "https://armatrac.com/tractor/290/1104-lux",
    label: "1104 Lux",
    productId: "cmsup2sr7000emkhkh1tyzrgy",
    matchName: "1104 Lux Cabin",
    match: "LIKELY",
    notes: ["Emër: 1104 Lux → 1104 Lux Cabin. HP 110 dhe Stage IIIA përputhen."],
    identityConflicts: [],
    generationSafe: true,
    description:
      "1104 Lux Cabin është një traktor ArmaTrac për përdorim në fushë, në klasën 110 HP. Motori Perkins dhe kabina e bëjnë të përshtatshëm për punë të gjata në terren.",
    facts: {
      emission: "Stage 3A",
      modelName: "1104 Lux",
      serie: "Lux",
      axle: null,
      cabinType: null,
      horsePower: 110,
      usageType: "Field",
      gear: null,
      engine: "Perkins",
      torque: "416 Nm",
      liftingCapacity: null,
      airConditioning: "Standard",
    },
  },
  {
    id: "1054e-crd5",
    url: "https://armatrac.com/tractor/269/1054e--crd5",
    label: "1054e+ CRD5",
    productId: "cmsup2sqx000dmkhkjy8bc1s0",
    matchName: "1054e Cabin",
    match: "CONFLICT",
    notes: ["Jeneracion i ndryshëm: 1054e Cabin 102 HP Stage IIIA kundrejt 1054e+ CRD5 105 HP Stage V."],
    identityConflicts: ["horsePower: 102 vs 105", "stage: Stage IIIA vs Stage V", "name: 1054e Cabin vs 1054e+ CRD5"],
    generationSafe: false,
    description: null,
    facts: {
      emission: "Stage 5",
      modelName: "1054e+ CRD5",
      serie: "E+",
      axle: null,
      cabinType: null,
      horsePower: 105,
      usageType: "Field",
      gear: null,
      engine: "HCE STAGE-V (ECAPRA)",
      torque: "428 - 450 Nm",
      liftingCapacity: null,
      airConditioning: "Standard",
    },
  },
  {
    id: "704-fruit-garden-crd5",
    url: "https://armatrac.com/tractor/271/704-fruit-garden-crd5",
    label: "704 Fruit Garden CRD5",
    productId: null,
    matchName: null,
    match: "NO MATCH",
    notes: [
      "Nuk ka 704 Fruit Garden në database. 704e Cabin është Field / Stage IIIA — nuk është i njëjti produkt.",
    ],
    identityConflicts: [],
    generationSafe: false,
    description: null,
    facts: {
      emission: "Stage 5",
      modelName: "704 Fruit Garden CRD5",
      serie: "Fruit Garden",
      axle: null,
      cabinType: null,
      horsePower: null,
      usageType: "Orchard",
      gear: null,
      engine: "HCE STAGE-V (ECAPRA)",
      torque: "295 - 308 Nm",
      liftingCapacity: null,
      airConditioning: null,
    },
  },
  {
    id: "514-fruit-garden",
    url: "https://armatrac.com/tractor/234/514-fruit-garden",
    label: "514 Fruit Garden",
    productId: "cmsup2sjr0000mkhkegcot9ht",
    matchName: "514 T2 Rops",
    match: "LIKELY",
    notes: ["Emër: 514 Fruit Garden → 514 T2 Rops. 50 HP, Stage IIIA, Orchard, ROPS. Cabin Type=Orchard nuk u lexua si kabinë."],
    identityConflicts: [],
    generationSafe: true,
    description:
      "514 T2 Rops është një traktor ArmaTrac për pemishte, në klasën 50 HP. Motori Sonalika dhe tërheqja 4 WD e bëjnë të përshtatshëm për rreshta të ngushta.",
    facts: {
      emission: "Stage 3A",
      modelName: "514 Fruit Garden",
      serie: "Fruit Garden",
      axle: "4 WD",
      cabinType: "Orchard",
      horsePower: 50,
      usageType: "Orchard",
      gear: "8 F / 8 R",
      engine: "Sonalika",
      torque: "230 Nm",
      liftingCapacity: "2200 KG",
      airConditioning: "No",
    },
  },
  {
    id: "854-lux-cabin",
    url: "https://armatrac.com/tractor/80/854-lux-cabin",
    label: "854 Lux Cabin",
    productId: "cmsup2sq8000cmkhkgpp3vwwa",
    matchName: "854 Lux Cabin",
    match: "EXACT",
    notes: ["Identiteti përputhet. HP katalogu 83.6 mbahet (burimi liston 85 HP) — nuk ndryshohet."],
    identityConflicts: ["horsePower: 83.6 vs 85"],
    generationSafe: true,
    description:
      "854 Lux Cabin është një traktor ArmaTrac për përdorim në fushë, në klasën 83.6 HP. Transmisioni 16 F / 8 R dhe kapaciteti ngritës 3200 KG e mbështesin punën në fushë.",
    facts: {
      emission: "Stage 3A",
      modelName: "854 Lux Cabin",
      serie: "Lux",
      axle: "4 WD",
      cabinType: "Cabin",
      horsePower: 85,
      usageType: "Field",
      gear: "16 F / 8 R",
      engine: "Perkins",
      torque: "289 Nm",
      liftingCapacity: "3200 KG",
      airConditioning: "Yes",
    },
  },
  {
    id: "854e-cabin",
    url: "https://armatrac.com/tractor/72/854e-cabin",
    label: "854e Cabin",
    productId: "cmsup2spu000bmkhk9ezsjtz6",
    matchName: "854e Cabin",
    match: "EXACT",
    notes: ["Identiteti përputhet. HP katalogu 83.6 mbahet (burimi liston 85 HP) — nuk ndryshohet."],
    identityConflicts: ["horsePower: 83.6 vs 85"],
    generationSafe: true,
    description:
      "854e Cabin është një traktor ArmaTrac për përdorim në fushë, në klasën 83.6 HP. Motori Perkins dhe transmisioni 12 F / 12 R e mbështesin punën e përditshme.",
    facts: {
      emission: "Stage 3A",
      modelName: "854e Cabin",
      serie: "E",
      axle: "4 WD",
      cabinType: "Cabin",
      horsePower: 85,
      usageType: "Field",
      gear: "12 F / 12 R",
      engine: "Perkins",
      torque: "289 Nm",
      liftingCapacity: "2600 KG",
      airConditioning: "Yes",
    },
  },
  {
    id: "584e-crd5",
    url: "https://armatrac.com/tractor/251/584e-crd5",
    label: "584e CRD5",
    productId: "cmsup2spb000amkhkyeehnxs7",
    matchName: "584e Cabin",
    match: "LIKELY",
    notes: ["Stage conflict: Terra Ferro Stage IIIA, burimi Stage V / CRD5. Motor dhe çifti rrotullues nuk importohen."],
    identityConflicts: ["stage: Stage IIIA vs Stage V"],
    generationSafe: false,
    description:
      "584e Cabin është një traktor ArmaTrac për përdorim në fushë, në klasën 58 HP, me kabinë për punë të gjata në terren.",
    facts: {
      emission: "Stage 5",
      modelName: "584e CRD5",
      serie: "E",
      axle: null,
      cabinType: null,
      horsePower: 58,
      usageType: "Field",
      gear: null,
      engine: "HCE STAGE-V (ECAPRA)",
      torque: "251 - 280 Nm",
      liftingCapacity: null,
      airConditioning: "Standard",
    },
  },
  {
    id: "604e-crd5",
    url: "https://armatrac.com/tractor/253/604e-crd5",
    label: "604e CRD5",
    productId: "cmsup2sod0008mkhkxbd7i8xv",
    matchName: "604e Cabin",
    match: "CONFLICT",
    notes: ["HP 58 vs 60 dhe Stage IIIA vs Stage V — jeneracion i ndryshëm. Nuk përditësohet."],
    identityConflicts: ["horsePower: 58 vs 60", "stage: Stage IIIA vs Stage V"],
    generationSafe: false,
    description: null,
    facts: {
      emission: "Stage 5",
      modelName: "604e CRD5",
      serie: "E",
      axle: null,
      cabinType: null,
      horsePower: 60,
      usageType: "Field",
      gear: null,
      engine: "HCE STAGE-V (ECAPRA)",
      torque: "251 - 280 Nm",
      liftingCapacity: null,
      airConditioning: "Standard",
    },
  },
  {
    id: "614e-crd5",
    url: "https://armatrac.com/tractor/283/614e-crd5",
    label: "614e CRD5",
    productId: "cmsup2snr0007mkhkfhbw7qm7",
    matchName: "614e Rops",
    match: "CONFLICT",
    notes: [
      "614e Rops: Field Stage IIIA 58 HP vs burimi Field Stage V 60 HP.",
      "614 T2 Rops (ECapra) është Stage V por Orchard 58 HP — gjithashtu conflict.",
    ],
    identityConflicts: ["horsePower: 58 vs 60", "stage: Stage IIIA vs Stage V"],
    generationSafe: false,
    description: null,
    facts: {
      emission: "Stage 5",
      modelName: "614e CRD5",
      serie: "E",
      axle: null,
      cabinType: null,
      horsePower: 60,
      usageType: "Field",
      gear: null,
      engine: "HCE STAGE-V (ECAPRA)",
      torque: "251 - 280 Nm",
      liftingCapacity: null,
      airConditioning: null,
    },
  },
  {
    id: "514e-crd5",
    url: "https://armatrac.com/tractor/282/514e-crd5",
    label: "514e CRD5",
    productId: "cmsup2snf0006mkhk1go7li81",
    matchName: "514e Rops",
    match: "CONFLICT",
    notes: [
      "514e Rops: Field Stage IIIA vs burimi Field Stage V.",
      "514 T2 Rops (eCapra) është Stage V por Orchard — Field/Orchard conflict.",
    ],
    identityConflicts: ["stage: Stage IIIA vs Stage V"],
    generationSafe: false,
    description: null,
    facts: {
      emission: "Stage 5",
      modelName: "514e CRD5",
      serie: "E",
      axle: null,
      cabinType: null,
      horsePower: 50,
      usageType: "Field",
      gear: null,
      engine: "HCE STAGE-V (ECAPRA)",
      torque: "230 - 251 Nm",
      liftingCapacity: null,
      airConditioning: null,
    },
  },
  {
    id: "614e",
    url: "https://armatrac.com/tractor/232/614e-",
    label: "614e",
    productId: "cmsup2snr0007mkhkfhbw7qm7",
    matchName: "614e Rops",
    match: "CONFLICT",
    notes: ["Burimi është Orchard 60 HP Stage IIIA; Terra Ferro 614e Rops është Field 58 HP. Nuk përditësohet."],
    identityConflicts: ["usage: Field vs Orchard", "horsePower: 58 vs 60"],
    generationSafe: false,
    description: null,
    facts: {
      emission: "Stage 3A",
      modelName: "614e",
      serie: "E",
      axle: "4 WD",
      cabinType: "Orchard",
      horsePower: 60,
      usageType: "Orchard",
      gear: "8 F / 8 R",
      engine: "Sonalika",
      torque: "230 Nm",
      liftingCapacity: "2200 KG",
      airConditioning: "No",
    },
  },
  {
    id: "804-fruit-garden-cabin",
    url: "https://armatrac.com/tractor/286/804-fruit-garden-cabin",
    label: "804 Fruit Garden Cabin",
    productId: "cmsup2sm00003mkhkz48cd88j",
    matchName: "804.4 Orchard Cabin",
    match: "LIKELY",
    notes: ["Emër 804 vs 804.4. HP katalogu 75.5 mbahet (burimi liston 80 HP)."],
    identityConflicts: ["horsePower: 75.5 vs 80"],
    generationSafe: true,
    description:
      "804.4 Orchard Cabin është një traktor ArmaTrac për pemishte, në klasën 75.5 HP. Motori Perkins dhe kabina e ndihmojnë punën në frutorë.",
    facts: {
      emission: "Stage 3A",
      modelName: "804 Fruit Garden Cabin",
      serie: "Fruit Garden",
      axle: null,
      cabinType: null,
      horsePower: 80,
      usageType: "Orchard",
      gear: null,
      engine: "Perkins",
      torque: "307 Nm",
      liftingCapacity: null,
      airConditioning: null,
    },
  },
];

export const UPDATABLE_PRODUCT_IDS = [
  ...new Set(ARMATRAC_SOURCES.filter((source) => source.match === "EXACT" || source.match === "LIKELY").map((source) => source.productId).filter((id): id is string => Boolean(id))),
];
